apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: testdeployment
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - name: testpod
        image: docker.io/sarseneault/test
        ports:
        - containerPort: 4249

